#reload Wallpapers
# preload = ~/Pictures/Wallpapers/black_hole.png

# Set wallpaper
# wallpaper = eDP-1, ~/Pictures/Wallpapers/black_hole.png

wallpaper {
  monitor=
  path = ~/Pictures/Wallpapers/black_hole.png
  fit_mode=cover
}

# ipc setup
ipc=off

# splash
splash=off
